services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: package.json
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: sh /app/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
       - ./backend/data:/app/data
       - ./backend/db:/app/db
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - __pycache__/
        - action: rebuild
          path: ./backend/requirements.txt
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/APIhealth')"]
      interval: 10s
      timeout: 5s
      retries: 5